spring.application.name=football-tourament-web
server.port=8080
spring.thymeleaf.check-template-location=false

spring.datasource.url=jdbc:mysql://localhost:3306/TournamentDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.tomcat.max-part-count=200

momo.api-url=https://test-payment.momo.vn/gw_payment/transactionProcessor
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.access-key=F8BBA842ECF85
momo.return-url=http://localhost:8080/order/momo-return
momo.notify-url=http://localhost:8080/order/momo-notify
momo.partner-code=MOMO
momo.request-type=captureMoMoWallet

# File Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.resolve-lazily=true

# Tomcat configurations
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=104857600
server.tomcat.max-http-post-size=104857600
server.tomcat.max-parameter-count=5000
server.tomcat.max-post-size=104857600
server.max-http-header-size=65536
server.connection-timeout=60000



# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.springframework.security=DEBUG
